---
title: "R Notebook"
author: "Hayley Laubinger"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_notebook
editor_options: 
    chunk_output_type: inline
---

```{r}
plot(cars)
```


```{r}
library(tidyverse)
library(knitr)
library(xtable)
```



```{r}
anscombe
```
```{r}
ansc <-
  bind_cols(
    anscombe %>%
      select(matches("x")) %>%
      gather(dataset, "x"),
    anscombe %>%
      select(matches("y")) %>%
      gather(key, "y")
  ) %>%
  select(-key) %>%
  mutate(dataset = gsub("x", "", dataset)) %>%
  as_tibble()
    
```

# Wrangle Data
```{r}
ansc <-
  bind_cols(
    anscombe %>% 
      select(matches("x")) %>% 
      gather(dataset, "x"),
    anscombe %>% 
      select(matches("y")) %>% 
      gather(key, "y")
  ) %>%
  select(-key) %>% 
  mutate(dataset = gsub("x", "", dataset)) %>%  
  as_tibble()

```
```{r}
ansc
```
# Perform some calculations
```{r}
ansc %>%
  group_by(dataset) %>%
  summarize(
    mean_x = mean(x),
    stdev_x = sd(x),
    mean_y = mean(y),
    stdev_y = sd(y)
  )
```
# stage and commit method 3

# visulize data
```{r}
ansc %>% ggplot(aes(x, y, color = dataset)) + 
  geom_point() +
  facet_wrap(~dataset, ncol = 2)

```
# inset iris data
```{r}
head(iris)
```
# Make a better table
```{r}
kable(head(iris), 
      align= c("l", "c", "r", "c", "l"),
      col.names = c("Sepal Length", "Sepal Width", "Sepal Length", "Sepal Width", "Species"))
```
# Now you try
```{r}
kable(head(airquality)) 
      
```
```{r}
kable(head(airquality))
      align= c("l", "c", "r", "c", "l")
      col.names = c("Day","Month","Temp(°F)","Wind (mph)","Solar R(lang)","Ozone (ppb)")
```
# insert code chunk on kable(head(chick_lm))
```{r}
kable(head(chicks_lm))
```
# What happened?
# This shows the x values as negative for most meal types. This seems like they have lost weight
# use x_table to summarize
```{r}
trees_lm <- lm(Girth ~ Height, data = trees)

xtable(trees_lm) %>% kable()
```
# Typing Bernoulli equation
$$constant= p+\frac{1}{2}pV^2+Pgh$$
^[Footnotes added]

